#!/usr/local/bin/fish

shp2json $argv[1] |
geoproject 'd3.geoAlbersUsa().fitSize([975, 610], d)' |
ndjson-split 'd.features' |
ndjson-map 'd.id = d.properties.GEOID,
delete d.properties.final_secn,
delete d.properties.ERA5_Revis,
delete d.properties.MERRA2_Rev,
delete d.properties.County_S_2,
delete d.properties.STATEFP,
delete d.properties.COUNTYFP,
delete d.properties.COUNTYNS,
delete d.properties.AFFGEOID,
delete d.properties.GEOID,
delete d.properties.NAME,
delete d.properties.LSAD,
delete d.properties.ALAND,
delete d.properties.AWATER,
delete d.properties.COUNTYFP_1,
delete d.properties.AFFGEOID_1,
delete d.properties.NAME_1,
delete d.properties.County_S_1,
delete d.properties.Manufactur,
delete d.properties.PerCapit_2,
delete d.properties.Allindus_1,
delete d.properties.Construc_1,
delete d.properties.Informat_1,
delete d.properties.discussStd,
delete d.properties.GDP2018Std,
delete d.properties.FarmingStd,
delete d.properties.MiningStd,
delete d.properties.discuss_1,
delete d.properties.discussOpp,
delete d.properties.reducetax,
delete d.properties.reducetaxO,
delete d.properties.CO2limits,
delete d.properties.CO2limitsO,
delete d.properties.localoffic,
delete d.properties.localoff_1,
delete d.properties.governor,
delete d.properties.governorOp,
delete d.properties.congress,
delete d.properties.congressOp,
delete d.properties.president,
delete d.properties.presidentO,
delete d.properties.corporatio,
delete d.properties.corporat_1,
delete d.properties.citizens,
delete d.properties.citizensOp,
delete d.properties.regulate,
delete d.properties.regulateOp,
delete d.properties.supportRPS,
delete d.properties.supportR_1,
delete d.properties.drilloffsh,
delete d.properties.drilloff_1,
delete d.properties.drillANWR,
delete d.properties.drillANWRO,
delete d.properties.fundrenewa,
delete d.properties.fundrene_1,
delete d.properties.rebates,
delete d.properties.rebatesOpp,
delete d.properties.mediaweekl,
delete d.properties.mediawee_1,
delete d.properties.prienv,
delete d.properties.prienvOppo,
delete d.properties.teachGW,
delete d.properties.teachGWOpp,
delete d.properties.happening,
delete d.properties.happeningO,
delete d.properties.human,
delete d.properties.humanOppos,
delete d.properties.consensus,
delete d.properties.consensusO,
delete d.properties.worried,
delete d.properties.worriedOpp,
delete d.properties.personal,
delete d.properties.personalOp,
delete d.properties.harmUS,
delete d.properties.harmUSOppo,
delete d.properties.devharm,
delete d.properties.devharmOpp,
delete d.properties.futuregen,
delete d.properties.futuregenO,
delete d.properties.harmplants,
delete d.properties.harmplan_1,
delete d.properties.timing,
delete d.properties.timingOppo,
delete d.properties.affectweat,
delete d.properties.affectwe_1,
delete d.properties.PerCapit_1,
delete d.properties.GDP2018_1,
delete d.properties.Financeand,
delete d.properties.Realestate,
delete d.properties.P,
delete d.properties.Management,
delete d.properties.Administra,
delete d.properties.Educationa,
delete d.properties.Healthcare,
delete d.properties.Artsentert,
delete d.properties.Accommodat,
delete d.properties.Otherservi,
delete d.properties.Incomeinth,
delete d.properties.discussO_1,
delete d.properties.reducetaxS,
delete d.properties.reduceta_1,
delete d.properties.CO2limitsS,
delete d.properties.CO2limit_1,
delete d.properties.localoff_2,
delete d.properties.localoff_3,
delete d.properties.governorSt,
delete d.properties.governor_1,
delete d.properties.congressSt,
delete d.properties.congress_1,
delete d.properties.presidentS,
delete d.properties.presiden_1,
delete d.properties.corporat_2,
delete d.properties.corporat_3,
delete d.properties.citizensSt,
delete d.properties.citizens_1,
delete d.properties.regulateSt,
delete d.properties.regulate_1,
delete d.properties.supportR_2,
delete d.properties.supportR_3,
delete d.properties.drilloff_2,
delete d.properties.drilloff_3,
delete d.properties.drillANWRS,
delete d.properties.drillANW_1,
delete d.properties.fundrene_2,
delete d.properties.fundrene_3,
delete d.properties.rebatesStd,
delete d.properties.rebatesO_1,
delete d.properties.mediawee_2,
delete d.properties.mediawee_3,
delete d.properties.prienvStd,
delete d.properties.prienvOp_1,
delete d.properties.teachGWStd,
delete d.properties.teachGWO_1,
delete d.properties.happeningS,
delete d.properties.happenin_1,
delete d.properties.humanStd,
delete d.properties.humanOpp_1,
delete d.properties.consensusS,
delete d.properties.consensu_1,
delete d.properties.worriedStd,
delete d.properties.worriedO_1,
delete d.properties.personalSt,
delete d.properties.personal_1,
delete d.properties.harmUSStd,
delete d.properties.harmUSOp_1,
delete d.properties.devharmStd,
delete d.properties.devharmO_1,
delete d.properties.futuregenS,
delete d.properties.futurege_1,
delete d.properties.harmplan_2,
delete d.properties.harmplan_3,
delete d.properties.timingStd,
delete d.properties.timingOp_1,
delete d.properties.affectwe_2,
delete d.properties.affectwe_3,
delete d.properties.Agricult_1,
delete d.properties.UtilitiesS,
delete d.properties.Manufact_1,
delete d.properties.Wholesal_1,
delete d.properties.Retailtr_1,
delete d.properties.Transpor_1,
delete d.properties.Financea_1,
delete d.properties.Realesta_1,
delete d.properties.PStd,
delete d.properties.Manageme_1,
delete d.properties.Administ_1,
delete d.properties.Educatio_1,
delete d.properties.Healthca_1,
delete d.properties.Artsente_1,
delete d.properties.Accommod_1,
delete d.properties.Otherser_1,
delete d.properties.Incomein_1,
d.properties.Allindustr = parseFloat(d.properties.Allindustr),
d.properties.Farming = parseFloat(d.properties.Farming),
d.properties.Agricultur = parseFloat(d.properties.Agricultur),
d.properties.Mining = parseFloat(d.properties.Mining),
d.properties.Utilities = parseFloat(d.properties.Utilities),
d.properties.Constructi = parseFloat(d.properties.Constructi),
d.properties.Wholesalet = parseFloat(d.properties.Wholesalet),
d.properties.Retailtrad = parseFloat(d.properties.Retailtrad),
d.properties.Transporta = parseFloat(d.properties.Transporta),
d.properties.Informatio = parseFloat(d.properties.Informatio),
d.properties.Ecmi_00_19 = d.properties.Ecmi_00_19 === -9999 ? undefined : parseFloat(d.properties.Ecmi_00_19.toFixed(2)) / 10.0 * -4.0,
d.properties.Ecmi_80_19 = d.properties.Ecmi_80_19 === -9999 ? undefined : parseFloat(d.properties.Ecmi_80_19.toFixed(2)) / 10.0 * -4.0,
d.properties.Ecmi_80_99 = d.properties.Ecmi_80_99 === -9999 ? undefined : parseFloat(d.properties.Ecmi_80_99.toFixed(2)) / 10.0 * -4.0,
d.properties.Edef_00_19 = d.properties.Edef_00_19 === -9999 ? undefined : parseFloat(d.properties.Edef_00_19.toFixed(2)),
d.properties.Edef_80_19 = d.properties.Edef_80_19 === -9999 ? undefined : parseFloat(d.properties.Edef_80_19.toFixed(2)),
d.properties.Edef_80_99 = d.properties.Edef_80_99 === -9999 ? undefined : parseFloat(d.properties.Edef_80_99.toFixed(2)),
d.properties.Edry_00_19 = d.properties.Edry_00_19 === -9999 ? undefined : parseFloat(d.properties.Edry_00_19.toFixed(2)),
d.properties.Edry_80_19 = d.properties.Edry_80_19 === -9999 ? undefined : parseFloat(d.properties.Edry_80_19.toFixed(2)),
d.properties.Edry_80_99 = d.properties.Edry_80_99 === -9999 ? undefined : parseFloat(d.properties.Edry_80_99.toFixed(2)),
d.properties.Egw_00_19 = d.properties.Egw_00_19 === -9999 ? undefined : parseFloat(d.properties.Egw_00_19.toFixed(2)),
d.properties.Egw_80_19 = d.properties.Egw_80_19 === -9999 ? undefined : parseFloat(d.properties.Egw_80_19.toFixed(2)),
d.properties.Egw_80_99 = d.properties.Egw_80_99 === -9999 ? undefined : parseFloat(d.properties.Egw_80_99.toFixed(2)),
d.properties.Eht_00_19 = d.properties.Eht_00_19 === -9999 ? undefined : parseFloat(d.properties.Eht_00_19.toFixed(2)),
d.properties.Eht_80_19 = d.properties.Eht_80_19 === -9999 ? undefined : parseFloat(d.properties.Eht_80_19.toFixed(2)),
d.properties.Eht_80_99 = d.properties.Eht_80_99 === -9999 ? undefined : parseFloat(d.properties.Eht_80_99.toFixed(2)),
d.properties.Epet_00_19 = d.properties.Epet_00_19 === -9999 ? undefined : parseFloat(d.properties.Epet_00_19.toFixed(2)),
d.properties.Epet_80_19 = d.properties.Epet_80_19 === -9999 ? undefined : parseFloat(d.properties.Epet_80_19.toFixed(2)),
d.properties.Epet_80_99 = d.properties.Epet_80_99 === -9999 ? undefined : parseFloat(d.properties.Epet_80_99.toFixed(2)),
d.properties.Eprc_00_19 = d.properties.Eprc_00_19 === -9999 ? undefined : parseFloat(d.properties.Eprc_00_19.toFixed(2)),
d.properties.Eprc_80_19 = d.properties.Eprc_80_19 === -9999 ? undefined : parseFloat(d.properties.Eprc_80_19.toFixed(2)),
d.properties.Eprc_80_99 = d.properties.Eprc_80_99 === -9999 ? undefined : parseFloat(d.properties.Eprc_80_99.toFixed(2)),
d.properties.Ero_00_19 = d.properties.Ero_00_19 === -9999 ? undefined : parseFloat(d.properties.Ero_00_19.toFixed(2)),
d.properties.Ero_80_19 = d.properties.Ero_80_19 === -9999 ? undefined : parseFloat(d.properties.Ero_80_19.toFixed(2)),
d.properties.Ero_80_99 = d.properties.Ero_80_99 === -9999 ? undefined : parseFloat(d.properties.Ero_80_99.toFixed(2)),
d.properties.Ewet_00_19 = d.properties.Ewet_00_19 === -9999 ? undefined : parseFloat(d.properties.Ewet_00_19.toFixed(2)),
d.properties.Ewet_80_19 = d.properties.Ewet_80_19 === -9999 ? undefined : parseFloat(d.properties.Ewet_80_19.toFixed(2)),
d.properties.Ewet_80_99 = d.properties.Ewet_80_99 === -9999 ? undefined : parseFloat(d.properties.Ewet_80_99.toFixed(2)),
d.properties.Mcmi_00_19 = d.properties.Mcmi_00_19 === -9999 ? undefined : parseFloat(d.properties.Mcmi_00_19.toFixed(2)),
d.properties.Mcmi_80_19 = d.properties.Mcmi_80_19 === -9999 ? undefined : parseFloat(d.properties.Mcmi_80_19.toFixed(2)),
d.properties.Mcmi_80_99 = d.properties.Mcmi_80_99 === -9999 ? undefined : parseFloat(d.properties.Mcmi_80_99.toFixed(2)),
d.properties.Mdef_00_19 = d.properties.Mdef_00_19 === -9999 ? undefined : parseFloat(d.properties.Mdef_00_19.toFixed(2)),
d.properties.Mdef_80_19 = d.properties.Mdef_80_19 === -9999 ? undefined : parseFloat(d.properties.Mdef_80_19.toFixed(2)),
d.properties.Mdef_80_99 = d.properties.Mdef_80_99 === -9999 ? undefined : parseFloat(d.properties.Mdef_80_99.toFixed(2)),
d.properties.Mdry_00_19 = d.properties.Mdry_00_19 === -9999 ? undefined : parseFloat(d.properties.Mdry_00_19.toFixed(2)),
d.properties.Mdry_80_19 = d.properties.Mdry_80_19 === -9999 ? undefined : parseFloat(d.properties.Mdry_80_19.toFixed(2)),
d.properties.Mdry_80_99 = d.properties.Mdry_80_99 === -9999 ? undefined : parseFloat(d.properties.Mdry_80_99.toFixed(2)),
d.properties.Mgw_00_19 = d.properties.Mgw_00_19 === -9999 ? undefined : parseFloat(d.properties.Mgw_00_19.toFixed(2)),
d.properties.Mgw_80_19 = d.properties.Mgw_80_19 === -9999 ? undefined : parseFloat(d.properties.Mgw_80_19.toFixed(2)),
d.properties.Mgw_80_99 = d.properties.Mgw_80_99 === -9999 ? undefined : parseFloat(d.properties.Mgw_80_99.toFixed(2)),
d.properties.Mht_00_19 = d.properties.Mht_00_19 === -9999 ? undefined : parseFloat(d.properties.Mht_00_19.toFixed(2)),
d.properties.Mht_80_19 = d.properties.Mht_80_19 === -9999 ? undefined : parseFloat(d.properties.Mht_80_19.toFixed(2)),
d.properties.Mht_80_99 = d.properties.Mht_80_99 === -9999 ? undefined : parseFloat(d.properties.Mht_80_99.toFixed(2)),
d.properties.Mpet_00_19 = d.properties.Mpet_00_19 === -9999 ? undefined : parseFloat(d.properties.Mpet_00_19.toFixed(2)),
d.properties.Mpet_80_19 = d.properties.Mpet_80_19 === -9999 ? undefined : parseFloat(d.properties.Mpet_80_19.toFixed(2)),
d.properties.Mpet_80_99 = d.properties.Mpet_80_99 === -9999 ? undefined : parseFloat(d.properties.Mpet_80_99.toFixed(2)),
d.properties.Mprc_00_19 = d.properties.Mprc_00_19 === -9999 ? undefined : parseFloat(d.properties.Mprc_00_19.toFixed(2)),
d.properties.Mprc_80_19 = d.properties.Mprc_80_19 === -9999 ? undefined : parseFloat(d.properties.Mprc_80_19.toFixed(2)),
d.properties.Mprc_80_99 = d.properties.Mprc_80_99 === -9999 ? undefined : parseFloat(d.properties.Mprc_80_99.toFixed(2)),
d.properties.Mro_00_19 = d.properties.Mro_00_19 === -9999 ? undefined : parseFloat(d.properties.Mro_00_19.toFixed(2)),
d.properties.Mro_80_19 = d.properties.Mro_80_19 === -9999 ? undefined : parseFloat(d.properties.Mro_80_19.toFixed(2)),
d.properties.Mro_80_99 = d.properties.Mro_80_99 === -9999 ? undefined : parseFloat(d.properties.Mro_80_99.toFixed(2)),
d.properties.Mwet_00_19 = d.properties.Mwet_00_19 === -9999 ? undefined : parseFloat(d.properties.Mwet_00_19.toFixed(2)),
d.properties.Mwet_80_19 = d.properties.Mwet_80_19 === -9999 ? undefined : parseFloat(d.properties.Mwet_80_19.toFixed(2)),
d.properties.Mwet_80_99 = d.properties.Mwet_80_99 === -9999 ? undefined : parseFloat(d.properties.Mwet_80_99.toFixed(2)),
d.properties.Ncmi_00_19 = d.properties.Ncmi_00_19 === -9999 ? undefined : parseFloat(d.properties.Ncmi_00_19.toFixed(2)),
d.properties.Ncmi_80_19 = d.properties.Ncmi_80_19 === -9999 ? undefined : parseFloat(d.properties.Ncmi_80_19.toFixed(2)),
d.properties.Ncmi_80_99 = d.properties.Ncmi_80_99 === -9999 ? undefined : parseFloat(d.properties.Ncmi_80_99.toFixed(2)),
d.properties.Ndef_00_19 = d.properties.Ndef_00_19 === -9999 ? undefined : parseFloat(d.properties.Ndef_00_19.toFixed(2)),
d.properties.Ndef_80_19 = d.properties.Ndef_80_19 === -9999 ? undefined : parseFloat(d.properties.Ndef_80_19.toFixed(2)),
d.properties.Ndef_80_99 = d.properties.Ndef_80_99 === -9999 ? undefined : parseFloat(d.properties.Ndef_80_99.toFixed(2)),
d.properties.Ndry_00_19 = d.properties.Ndry_00_19 === -9999 ? undefined : parseFloat(d.properties.Ndry_00_19.toFixed(2)),
d.properties.Ndry_80_19 = d.properties.Ndry_80_19 === -9999 ? undefined : parseFloat(d.properties.Ndry_80_19.toFixed(2)),
d.properties.Ndry_80_99 = d.properties.Ndry_80_99 === -9999 ? undefined : parseFloat(d.properties.Ndry_80_99.toFixed(2)),
d.properties.Ngw_00_19 = d.properties.Ngw_00_19 === -9999 ? undefined : parseFloat(d.properties.Ngw_00_19.toFixed(2)),
d.properties.Ngw_80_19 = d.properties.Ngw_80_19 === -9999 ? undefined : parseFloat(d.properties.Ngw_80_19.toFixed(2)),
d.properties.Ngw_80_99 = d.properties.Ngw_80_99 === -9999 ? undefined : parseFloat(d.properties.Ngw_80_99.toFixed(2)),
d.properties.Nht_00_19 = d.properties.Nht_00_19 === -9999 ? undefined : parseFloat(d.properties.Nht_00_19.toFixed(2)),
d.properties.Nht_80_19 = d.properties.Nht_80_19 === -9999 ? undefined : parseFloat(d.properties.Nht_80_19.toFixed(2)),
d.properties.Nht_80_99 = d.properties.Nht_80_99 === -9999 ? undefined : parseFloat(d.properties.Nht_80_99.toFixed(2)),
d.properties.Npet_00_19 = d.properties.Npet_00_19 === -9999 ? undefined : parseFloat(d.properties.Npet_00_19.toFixed(2)),
d.properties.Npet_80_19 = d.properties.Npet_80_19 === -9999 ? undefined : parseFloat(d.properties.Npet_80_19.toFixed(2)),
d.properties.Npet_80_99 = d.properties.Npet_80_99 === -9999 ? undefined : parseFloat(d.properties.Npet_80_99.toFixed(2)),
d.properties.Nprc_00_19 = d.properties.Nprc_00_19 === -9999 ? undefined : parseFloat(d.properties.Nprc_00_19.toFixed(2)),
d.properties.Nprc_80_19 = d.properties.Nprc_80_19 === -9999 ? undefined : parseFloat(d.properties.Nprc_80_19.toFixed(2)),
d.properties.Nprc_80_99 = d.properties.Nprc_80_99 === -9999 ? undefined : parseFloat(d.properties.Nprc_80_99.toFixed(2)),
d.properties.Nro_00_19 = d.properties.Nro_00_19 === -9999 ? undefined : parseFloat(d.properties.Nro_00_19.toFixed(2)),
d.properties.Nro_80_19 = d.properties.Nro_80_19 === -9999 ? undefined : parseFloat(d.properties.Nro_80_19.toFixed(2)),
d.properties.Nro_80_99 = d.properties.Nro_80_99 === -9999 ? undefined : parseFloat(d.properties.Nro_80_99.toFixed(2)),
d.properties.Nwet_00_19 = d.properties.Nwet_00_19 === -9999 ? undefined : parseFloat(d.properties.Nwet_00_19.toFixed(2)),
d.properties.Nwet_80_19 = d.properties.Nwet_80_19 === -9999 ? undefined : parseFloat(d.properties.Nwet_80_19.toFixed(2)),
d.properties.Nwet_80_99 = d.properties.Nwet_80_99 === -9999 ? undefined : parseFloat(d.properties.Nwet_80_99.toFixed(2)),
d.properties.PercentPop = d.properties.PercentPop === -9999 ? undefined : parseFloat(d.properties.PercentPop.toFixed(2)) * 100,
d.properties.PercentP_1 = d.properties.PercentP_1 === -9999 ? undefined : parseFloat(d.properties.PercentP_1.toFixed(2)) * 100,
d.properties.PercentNon = d.properties.PercentNon === -9999 ? undefined : parseFloat(d.properties.PercentNon.toFixed(2)) * 100,
d.properties.PercentofP = d.properties.PercentofP === -9999 ? undefined : parseFloat(d.properties.PercentofP.toFixed(2)) * 100,
d.properties.PercentP_2 = d.properties.PercentP_2 === -9999 ? undefined : parseFloat(d.properties.PercentP_2.toFixed(2)),
d.properties.PercentP_3 = d.properties.PercentP_3 === -9999 ? undefined : parseFloat(d.properties.PercentP_3.toFixed(2)),
d.properties.PercentN_1 = d.properties.PercentN_1 === -9999 ? undefined : parseFloat(d.properties.PercentN_1.toFixed(2)),
d.properties.Percento_1 = d.properties.Percento_1 === -9999 ? undefined : parseFloat(d.properties.Percento_1.toFixed(2)),
d' > temp-map.ndjson
geo2topo -n counties=temp-map.ndjson |
toposimplify -p -1 -f |
topoquantize 1e5 |
topomerge -k 'd.id.slice(0,2)' states=counties > usa-topo.json